### ISSUE TITLE
Getting it to build

### ISSUE THREAD

**Issue by alexandre-g** [giginet/Scipio#1]
Hi there! Thanks for contributing to the community.

I am failing at running the following command:
`swift run scipio`
Can you confirm it working for you? And if so, which tooling are you using.

I am trying with Xcode 14.0.1

Tried to work around a couple of errors (changing macos to macosx, adding quotes to Any Mac) but stuck at the following
```
The following build commands failed:
SwiftEmitModule normal x86_64 Emitting\ module\ for\ TSCBasic (in target 'TSCBasic' from project 'Scipio')
SwiftEmitModule normal arm64 Emitting\ module\ for\ TSCBasic (in target 'TSCBasic' from project 'Scipio')
```

**Comment by giginet** [comment]
Hi. I develop this product on Xcode 14.0.
I tried to build on Xcode 14.0.1. However, it works well.

Do you have any information?

I'm going to add a CI environment to this repo.

**Comment by alexandre-g** [comment]
@giginet I poked around a bit more and could get a build out by archiving from Xcode (instead of invoking via `swift run scipio`)

I think it would be good to have some instructions on the Readme for how to get the thing installed for those new to SPM

**Comment by giginet** [comment]
Currently, default command is `prepare`. So `swift run scipio` means `scipio prepare .`.
Scipio tries to build frameworks in Package.swift on the current directory.
I guess it failed to build current manifests. Could you prepare a valid `Package.swift`?
You can see a detail with `--verbose` option.

This product is under development. So documentation and error feedback is not very fulfilling. sorry for your inconvenience.

**Comment by alexandre-g** [comment]
All good! Thanks for the explanation
