### ISSUE TITLE
Issues with `firebase-ios-sdk`

### ISSUE THREAD

**Issue by dmhts** [giginet/Scipio#139]
Hey @giginet ,

I've been recently having some issues while trying to use `Scipio` with [firebase-ios-sdk](https://github.com/firebase/firebase-ios-sdk/). Specifically, the Firebase SDK depends on [GoogleUtilites](https://github.com/google/GoogleUtilities), which cannot be precompiled due to missing symbols.

### Details:
- If I try to compile the [GoogleUtilities](https://github.com/google/GoogleUtilities) package either via Xcode or via the CLI it all works well:
```
cd GoogleUtilities
swift build
Building for debugging...
[38/38] Compiling GoogleUtilities...
Build complete! (2.95s)
```
- If I try to use `Scipio` on it, it fails with the missing symbol error:
```
cd GoogleUtilities
scipio create --platforms iOS
🔁 Resolving Dependencies...
📦 Building third-party-IsAppEncrypted for iOS
🚀 Combining into XCFramework...
📦 Building GoogleUtilities-Environment for iOS
[GoogleUtilities-Environment#30] failed
...
[GoogleUtilities-Environment#30] Undefined symbols for architecture arm64:
  "_IsAppEncrypted", referenced from:
      ___39+[GULAppEnvironmentUtil isFromAppStore]_block_invoke in GULAppEnvironmentUtil.o
ld: symbol(s) not found for architecture arm64
```

If you look at the manifest, [the GoogleUtilities-Environment target](https://github.com/google/GoogleUtilities/blob/main/Package.swift#L85-L87) (which fails to compile) has only one dependency to [third-party-IsAppEncrypted](https://github.com/google/GoogleUtilities/blob/main/Package.swift#L96-L104) with [a single Obj-C implementation file](https://github.com/google/GoogleUtilities/tree/main/third_party/IsAppEncrypted) in it, and as you in the log the target is successfully precompiled at the previous. Yet, for some reason, `Scipio` (well not Scipio, but the instructed linker) cannot find symbols from the precompiled target.

The rather unusual thing is that both targets are written in `Obj-C`. Could it be an issue with module maps or similar? I can attach the `.pif` file if it helps.

Have you already tried to use `Scipio` with the Firebase SDK? It's arguably one of the most popular iOS libraries out there and it would be really great if `Scipio` could build it. 

Are there maybe some known issues with `Obj-C` targets? I'm asking because there are similar problems with other Obj-C packages that Firebase depends on, such as FBLPromise, but it could be the very same issue.

I am willing to dig deeper into the issue if you could show me the direction.

**Comment by omartio** [comment]
I have the similar issue with Firebase.
```
[GoogleUtilities-Environment#66] Undefined symbol: _FBLPromiseErrorDomain
[GoogleUtilities-Environment#66] Undefined symbol: _IsAppEncrypted
[GoogleUtilities-Environment#66] Undefined symbol: _OBJC_CLASS_$_FBLPromise
[GoogleUtilities-Environment#66] Linker command failed with exit code 1 (use -v to see invocation)
[GoogleUtilities-Environment#66] Undefined symbols for architecture x86_64:
  "_FBLPromiseErrorDomain", referenced from:
      ___62-[GULKeychainStorage getObjectForKey:objectClass:accessGroup:]_block_invoke in GULKeychainStorage.o
  "_IsAppEncrypted", referenced from:
      ___39+[GULAppEnvironmentUtil isFromAppStore]_block_invoke in GULAppEnvironmentUtil.o
  "_OBJC_CLASS_$_FBLPromise", referenced from:
       in GULKeychainStorage.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

[GoogleUtilities-Environment#66] failed
[GoogleUtilities-Environment#67] cancelled
[GoogleUtilities-Environment] completed
build cancelled
🚀 Combining into XCFramework...
Something went wrong during building
Please execute with --verbose option.
Execution was terminated:
error: the path does not point to a valid framework: ../.build/scipio/AssembledFrameworks/Release-iphonesimulator/GoogleUtilities_Environment.framework


Error: Execution was terminated:
error: the path does not point to a valid framework: ../.build/scipio/AssembledFrameworks/Release-iphonesimulator/GoogleUtilities_Environment.framework
```

**Comment by Mo7amedFouad** [comment]
According to this issue here https://github.com/giginet/Scipio/issues/112 
using `--framework-type static` is the way to go. I managed to compile the Firebase dependency successfully using the following command 
```scipio create --platforms iOS --framework-type static --embed-debug-symbols --support-simulators``` 
I'm still not sure why we can't link Obj-c only frameworks as dynamic 🤷

**Comment by dmhts** [comment]
Oh, thanks Mo! And btw nice to see you here :)

**Comment by giginet** [comment]
Sorry for the late reply.

And thanks to those who answered!
As far as I can confirm, Firebase builds can't be built with dynamic mode.
I don't think there is enough documentation, so I'll prepare some troubleshooting etc.
