### ISSUE TITLE
Support for Explicitly built modules

### ISSUE THREAD

**Issue by mackoj** [giginet/Scipio#159]
Hello,

Do you think adding support for `Explicitly built modules` will be useful for Scipio ?

- https://developer.apple.com/videos/play/wwdc2024/10171/
- https://useyourloaf.com/blog/xcode-explicitly-built-modules/
- https://bitrise.io/blog/post/demystifying-explicitly-built-modules-for-xcode

**Comment by giginet** [comment]
Hi! I don't plan to enable Explicitly built modules, however, you can pass any XCConfig to use `extraBuildParameters` option
