### ISSUE TITLE
How about adding option to enable `-allow-internal-distribution` for making library-evolution not supported libraries?

### ISSUE THREAD

**Issue by muukii** [giginet/Scipio#48]
I just thought something from seeing this issue (https://github.com/giginet/Scipio/issues/32)
Some frameworks might be failed to build as XCFramework with enabling library-evolution.

xcodebuild command supports to make XCFramework without library-evolution, means not having `.swiftinterface`.
with this, the build process will be the same as to build process using packages normal way.

If using Scipio is for build cache, it works with not enabling library evolution in popular cases.

So I propose Scipo supports using a option (--allow-internal-distribution)
just like Realm doing https://github.com/realm/realm-swift/blob/master/build.sh#L166

```
xcodebuild -create-xcframework -allow-internal-distribution -output "$xcframework_path" \
        -framework "$os_path" -framework "$simulator_path"
```

this approach comes from [my previous outdated work](https://github.com/muukii/cocoapods-frost).
I was stuck in building prebuilt binary using cocoapods. some libraries failed to build with library-evolution.
Also I've seen .swiftinterface was wrong before.

And I appreciate your great work.
I hope this library helps saving build time.

**Comment by giginet** [comment]
I'm working on this here. https://github.com/giginet/Scipio/pull/49 😄

**Comment by muukii** [comment]
wow, glad to hear that! Thank you!
