### ISSUE TITLE
Cache is not reused every time.

### ISSUE THREAD

**Issue by mtj0928** [giginet/Scipio#55]
Scipio generates a version file for each dependency, and a cache is reused when the `CacheKey` of the generated file is equal.
However, `sdks` in a version file is a set and the order of `sdks` are not same every time.
As a result, the key will be changed.

The bellow version files represents the same version, but the order of `sdks` is not equal.
```
{
  "buildOptions" : {
    "enableLibraryEvolution" : true,
    "buildConfiguration" : "release",
    "isDebugSymbolsEmbedded" : true,
    "frameworkType" : "static",
    "sdks" : [
      "iOS",
      "iOSSimulator"
    ]
  },
  "targetName" : "Alamofire",
  "clangVersion" : "clang-1403.0.22.11",
  "pin" : {
    "version" : "5.6.4",
    "revision" : "78424be314842833c04bc3bef5b72e85fff99204"
  }
}
```
```
{
  "buildOptions" : {
    "enableLibraryEvolution" : true,
    "buildConfiguration" : "release",
    "isDebugSymbolsEmbedded" : true,
    "frameworkType" : "static",
    "sdks" : [
      "iOSSimulator",
      "iOS"
    ]
  },
  "targetName" : "Alamofire",
  "clangVersion" : "clang-1403.0.22.11",
  "pin" : {
    "version" : "5.6.4",
    "revision" : "78424be314842833c04bc3bef5b72e85fff99204"
  }
}
```

**Comment by freddi-kit** [comment]
sdks may not Set? @giginet

**Comment by mtj0928** [comment]
Mose of `sdks` are `OrderedSet`, but I found `Set<SDK>` here.
https://github.com/giginet/Scipio/blob/6a50d051f0910a0a8367c1a82c5ad9b69243cb3a/Sources/ScipioKit/Runner.swift#L279-L283
