### ISSUE TITLE
platforms指定が空のプロジェクトでエラーになる

### ISSUE THREAD

**Issue by omochi** [giginet/Scipio#76]
prepareコマンドを swift-nio プロジェクトに対して実行したところ、下記エラーが出ました。

```
Error: Any platforms are not spcified in Package.swift
```

swift-nioのように、
macOS, iOS, tvOS, watchOS 全ての下限バージョンに対応しているようなプロジェクトにおいては、
platforms指定は記述しないのが理想の設定方法ですから、
指定が無い事をエラーにするのではなく、
4つのプラットフォームが指定されているものとして動作してほしいです。

**Comment by giginet** [comment]
`prepare` コマンドは複数の依存関係を準備するためのコマンドで、単体のパッケージをフレームワーク化する場合は `create` コマンドを推奨しています。

`create` には `--platform` オプションがあるので指定可能です。

`prepare`はアプリケーションの依存を用意するために専用のPackage Manifestを作ることを想定したコマンドで、platform指定を敢えて必須にしています。

**Comment by omochi** [comment]
なるほど。 `create` コマンドというのもあるんですね。
READMEにも書かれているのを見つけました。

`prepare` の対象は
複数のライブラリをscipioに指定するために専用に定義される特殊なパッケージ定義であり、
そのために用意するからplatformsを書けるということですね。

`create` の対象は既存のパッケージ定義であり、
変更しないことを想定しているので、
必要であればコマンド側で `--platform` を指定できるようにしているのですね。

ありがとうございました。
