### ISSUE TITLE
Installation Guide for newbies

### ISSUE THREAD

**Issue by prathumca** [giginet/Scipio#77]
I would like to understand how to install `scipio` on the mac. Though [Readme.md ](https://github.com/giginet/Scipio/blob/main/README.md)provides great insights how to use but it lacks the support how to integrate it with any project. Any help greatly appreciated.

**Comment by prathumca** [comment]
For any newbies looking for installation guide, here are steps:

1. Download or clone the Scipio to your computer and unzip it.
2. Now open terminal and cd to the Scipio folder, for e.x: `cd /Users/itsme/Desktop/Scipio-0.15.0`
3. Now run `swift build`
4. Once the build is completed you see a **hidden** folder `.build` on the current directory. Ensure that on your mac hidden folders are enabled/shown.
5. Navigate to `.build/arm64-apple-macosx/debug` and find `scipio` executable.
6. Copy the `scipio` to` /usr/local/bin` 
7. Bingo you are ready to use `scipio' on your mac.

Note: This is done silicon mac, for intel based the for path of `scipio' might be at a different location.

**Comment by giginet** [comment]
Hi. I added the installation guide.
https://giginet.github.io/Scipio/documentation/scipio/installation
